import { GameItem } from './types';

export const INITIAL_CURRENCY = 2500;

export const FURNITURE_ITEMS: GameItem[] = [
  {
    id: 'sofa_blue',
    name: 'Cloud Sofa',
    type: 'furniture',
    price: 500,
    description: 'A super soft blue sofa that feels like a cloud.',
    width: 3,
    height: 1,
    color: '#60a5fa',
    iconName: 'Armchair',
  },
  {
    id: 'table_oak',
    name: 'Oak Coffee Table',
    type: 'furniture',
    price: 150,
    description: 'Sturdy oak table for your coffee and books.',
    width: 2,
    height: 1,
    color: '#d97706',
    iconName: 'Table',
  },
  {
    id: 'rug_persian',
    name: 'Vintage Rug',
    type: 'surface',
    price: 300,
    description: 'Adds a touch of class to any room.',
    width: 3,
    height: 2,
    color: '#be185d',
    iconName: 'Rug',
  },
  {
    id: 'plant_monstera',
    name: 'Potted Monstera',
    type: 'plant',
    price: 80,
    description: 'Needs sunlight and love.',
    width: 1,
    height: 1,
    color: '#15803d',
    iconName: 'Flower',
  },
  {
    id: 'lamp_floor',
    name: 'Arc Floor Lamp',
    type: 'lighting',
    price: 120,
    description: 'Modern lighting for reading corners.',
    width: 1,
    height: 1,
    color: '#fcd34d',
    iconName: 'Lamp',
  },
  {
    id: 'bookshelf_tall',
    name: 'Tall Bookshelf',
    type: 'furniture',
    price: 200,
    description: 'Holds all your knowledge.',
    width: 2,
    height: 1,
    color: '#78350f',
    iconName: 'Library',
  },
  {
    id: 'chair_accent',
    name: 'Yellow Accent Chair',
    type: 'furniture',
    price: 180,
    description: 'Pop of color for your living room.',
    width: 1,
    height: 1,
    color: '#fbbf24',
    iconName: 'Armchair',
  },
];
